// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tunepool.Repository;

#nullable disable

namespace tunepool.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260129184549_ADD TOKEN TYPE AND SCOPE")]
    partial class ADDTOKENTYPEANDSCOPE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tunepool.Repository.Model.platform.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlatForm");
                });

            modelBuilder.Entity("tunepool.Repository.Model.playlist.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("platform_id")
                        .HasColumnType("int");

                    b.Property<string>("playList_Urls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("platform_id");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("tunepool.Repository.Model.playlistTags.PlaylistTags", b =>
                {
                    b.Property<int>("playlist_id")
                        .HasColumnType("int");

                    b.Property<int>("tags_id")
                        .HasColumnType("int");

                    b.HasKey("playlist_id", "tags_id");

                    b.HasIndex("tags_id");

                    b.ToTable("PlaylistTags");
                });

            modelBuilder.Entity("tunepool.Repository.Model.popularity.Popularity", b =>
                {
                    b.Property<int>("playListId")
                        .HasColumnType("int");

                    b.Property<int>("hearts")
                        .HasColumnType("int");

                    b.Property<int>("likes")
                        .HasColumnType("int");

                    b.HasKey("playListId");

                    b.ToTable("Popularity");
                });

            modelBuilder.Entity("tunepool.Repository.Model.serviceProviderToken.ServiceProviderToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SCaccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SCexpiresIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SCrefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCscope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("tokenType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviderToken");
                });

            modelBuilder.Entity("tunepool.Repository.Model.tags.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("tunepool.Repository.Model.playlist.Playlist", b =>
                {
                    b.HasOne("tunepool.Repository.Model.platform.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("platform_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("tunepool.Repository.Model.playlistTags.PlaylistTags", b =>
                {
                    b.HasOne("tunepool.Repository.Model.playlist.Playlist", "Playlist")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("playlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tunepool.Repository.Model.tags.Tags", "Tags")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("tags_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("tunepool.Repository.Model.popularity.Popularity", b =>
                {
                    b.HasOne("tunepool.Repository.Model.playlist.Playlist", "Playlist")
                        .WithMany("Popularity")
                        .HasForeignKey("playListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("tunepool.Repository.Model.playlist.Playlist", b =>
                {
                    b.Navigation("PlaylistTags");

                    b.Navigation("Popularity");
                });

            modelBuilder.Entity("tunepool.Repository.Model.tags.Tags", b =>
                {
                    b.Navigation("PlaylistTags");
                });
#pragma warning restore 612, 618
        }
    }
}
